#!/bin/sh
./local-hol-heap --gcthreads=1  <<'__end-of-file__'
val _ = PolyML.Compiler.prompt1:="";
val _ = PolyML.Compiler.prompt2:="";
val _ = PolyML.print_depth 0;
val _ = List.map load ["testgen"] handle x => ((case x of Fail s => print (s^"\n") | _ => ()); OS.Process.exit OS.Process.failure);
__end-of-file__
